image:
  file: .gitpod.Dockerfile

# Command to start on workspace startup
tasks:
  - command: zsh
  # - init: gh auth login
  - command: cd .. && jupyter-lab --ContentsManager.allow_hidden=True

# Ports to expose on workspace startup
ports:
  - port: 8888
    onOpen: open-preview